# Generated by Django 2.2.7 on 2020-07-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='additional_info',
            new_name='solution',
        ),
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.URLField(default=None, null=True),
        ),
    ]
