# Generated by Django 2.2.7 on 2020-07-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200719_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='threat',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.TextField(default=None, null=True),
        ),
    ]
