# Generated by Django 2.2.7 on 2020-07-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200719_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='verbal',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
